set(_CATKIN_CURRENT_PACKAGE "kinect2grabber")
set(kinect2grabber_VERSION "0.0.0")
set(kinect2grabber_MAINTAINER "Michele Mambrini <michelemambrini@gmail.com>, Giacomo Dabisias <giacomo.dabisias@gmail.com>")
set(kinect2grabber_PACKAGE_FORMAT "1")
set(kinect2grabber_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "pcl_conversions" "pcl_ros" "sensor_msgs" "geometry_msgs" "tf" "cmake_modules" "cv_bridge" "image_transport")
set(kinect2grabber_BUILD_EXPORT_DEPENDS "rospy" "cv_bridge" "roscpp" "std_msgs" "pcl_conversions" "pcl_ros" "sensor_msgs" "geometry_msgs" "tf" "cmake_modules" "image_transport")
set(kinect2grabber_BUILDTOOL_DEPENDS "catkin")
set(kinect2grabber_BUILDTOOL_EXPORT_DEPENDS )
set(kinect2grabber_EXEC_DEPENDS "rospy" "cv_bridge" "roscpp" "std_msgs" "pcl_conversions" "pcl_ros" "sensor_msgs" "geometry_msgs" "tf" "cmake_modules" "image_transport")
set(kinect2grabber_RUN_DEPENDS "rospy" "cv_bridge" "roscpp" "std_msgs" "pcl_conversions" "pcl_ros" "sensor_msgs" "geometry_msgs" "tf" "cmake_modules" "image_transport")
set(kinect2grabber_TEST_DEPENDS )
set(kinect2grabber_DOC_DEPENDS )
set(kinect2grabber_URL_WEBSITE "")
set(kinect2grabber_URL_BUGTRACKER "")
set(kinect2grabber_URL_REPOSITORY "")
set(kinect2grabber_DEPRECATED "")